name: plant_disease_detector
description: Plant disease detection app

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  tflite_flutter: ^0.11.0  # Ensure this is included
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  intl: ^0.20.2
  http: ^1.5.0
  image: ^3.0.1
  # Additional dependencies
  provider: ^6.0.0  # For state management
  flutter_bloc: ^8.0.0  # For BLoC pattern (optional)
  dio: ^5.0.0  # For advanced HTTP requests (optional)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/model_quant.tflite
    - assets/labels.txt

